export const GET_ALL_BBDGKT = 'GET_ALL_BBDGKT';
export const GET_ALL_BBDGKT_SUCCESS = 'GET_ALL_BBDGKT_SUCCESS';
export const GET_ALL_BBDGKT_FAIL = 'GET_ALL_BBDGKT_FAIL';

export const SEARCH_BBDGKT = 'SEARCH_BBDGKT';
export const SEARCH_BBDGKT_SUCCESS = 'SEARCH_BBDGKT_SUCCESS';
export const SEARCH_BBDGKT_FAIL = 'SEARCH_BBDGKT_FAIL';

export const GET_ID_BBDGKT = 'GET_ID_BBDGKT';
export const GET_ID_BBDGKT_SUCCESS = 'GET_ID_BBDGKT_SUCCESS';
export const GET_ID_BBDGKT_FAIL = 'GET_ID_BBDGKT_FAIL';

export const ADD_BBDGKT = 'ADD_BBDGKT';
export const ADD_BBDGKT_SUCCESS = 'ADD_BBDGKT_SUCCESS';
export const ADD_BBDGKT_FAIL = 'ADD_BBDGKT_FAIL';

export const DELETE_BBDGKT = 'DELETE_BBDGKT';
export const DELETE_BBDGKT_SUCCESS = 'DELETE_BBDGKT_SUCCESS';
export const DELETE_BBDGKT_FAIL = 'DELETE_BBDGKT_FAIL';

export const UPDATE_BBDGKT = 'UPDATE_BBDGKT';
export const UPDATE_BBDGKT_SUCCESS = 'UPDATE_BBDGKT_SUCCESS';
export const UPDATE_BBDGKT_NOTE = 'UPDATE_BBDGKT_NOTE';
export const UPDATE_BBDGKT_FAIL = 'UPDATE_BBDGKT_FAIL';
export const SET_BBDGKT_EDITING ='SET_BBDGKT_EDITING';