export const GET_ALL_BPTC = 'GET_ALL_BPTC';
export const GET_ALL_BPTC_SUCCESS = 'GET_ALL_BPTC_SUCCESS';
export const GET_ALL_BPTC_FAIL = 'GET_ALL_BPTC_FAIL';

export const SEARCH_BPTC = 'SEARCH_BPTC';
export const SEARCH_BPTC_SUCCESS = 'SEARCH_BPTC_SUCCESS';
export const SEARCH_BPTC_FAIL = 'SEARCH_BPTC_FAIL';

export const GET_ID_BPTC = 'GET_ID_BPTC';
export const GET_ID_BPTC_SUCCESS = 'GET_ID_BPTC_SUCCESS';
export const GET_ID_BPTC_FAIL = 'GET_ID_BPTC_FAIL';

export const ADD_BPTC = 'ADD_BPTC';
export const ADD_BPTC_SUCCESS = 'ADD_BPTC_SUCCESS';
export const ADD_BPTC_FAIL = 'ADD_BPTC_FAIL';

export const DELETE_BPTC = 'DELETE_BPTC';
export const DELETE_BPTC_SUCCESS = 'DELETE_BPTC_SUCCESS';
export const DELETE_BPTC_FAIL = 'DELETE_BPTC_FAIL';

export const UPDATE_BPTC = 'UPDATE_BPTC';
export const UPDATE_BPTC_SUCCESS = 'UPDATE_BPTC_SUCCESS';
export const UPDATE_BPTC_NOTE = 'UPDATE_BPTC_NOTE';
export const UPDATE_BPTC_FAIL = 'UPDATE_BPTC_FAIL';
export const SET_BPTC_EDITING ='SET_BPTC_EDITING';