export const GET_ALL_CCHTTS = 'GET_ALL_CCHTTS';
export const GET_ALL_CCHTTS_SUCCESS = 'GET_ALL_CCHTTS_SUCCESS';
export const GET_ALL_CCHTTS_FAIL = 'GET_ALL_CCHTTS_FAIL';

export const SEARCH_CCHTT = 'SEARCH_CCHTT';
export const SEARCH_CCHTT_SUCCESS = 'SEARCH_CCHTT_SUCCESS';
export const SEARCH_CCHTT_FAIL = 'SEARCH_CCHTT_FAIL';

export const GET_ID_CCHTT = 'GET_ID_CCHTT';
export const GET_ID_CCHTT_SUCCESS = 'GET_ID_CCHTT_SUCCESS';
export const GET_ID_CCHTT_FAIL = 'GET_ID_CCHTT_FAIL';

export const ADD_CCHTT = 'ADD_CCHTT';
export const ADD_CCHTT_SUCCESS = 'ADD_CCHTT_SUCCESS';
export const ADD_CCHTT_FAIL = 'ADD_CCHTT_FAIL';

export const DELETE_CCHTT = 'DELETE_CCHTT';
export const DELETE_CCHTT_SUCCESS = 'DELETE_CCHTT_SUCCESS';
export const DELETE_CCHTT_FAIL = 'DELETE_CCHTT_FAIL';

export const UPDATE_CCHTT = 'UPDATE_CCHTT';
export const UPDATE_CCHTT_SUCCESS = 'UPDATE_CCHTT_SUCCESS';
export const UPDATE_CCHTT_NOTE = 'UPDATE_CCHTT_NOTE';
export const UPDATE_CCHTT_FAIL = 'UPDATE_CCHTT_FAIL';
export const SET_CCHTT_EDITING ='SET_CCHTT_EDITING';