export const GET_ALL_CGSATS = 'GET_ALL_CGSATS';
export const GET_ALL_CGSATS_SUCCESS = 'GET_ALL_CGSATS_SUCCESS';
export const GET_ALL_CGSATS_FAIL = 'GET_ALL_CGSATS_FAIL';

export const SEARCH_CGSAT = 'SEARCH_CGSAT';
export const SEARCH_CGSAT_SUCCESS = 'SEARCH_CGSAT_SUCCESS';
export const SEARCH_CGSAT_FAIL = 'SEARCH_CGSAT_FAIL';

export const GET_ID_CGSAT = 'GET_ID_CGSAT';
export const GET_ID_CGSAT_SUCCESS = 'GET_ID_CGSAT_SUCCESS';
export const GET_ID_CGSAT_FAIL = 'GET_ID_CGSAT_FAIL';

export const ADD_CGSAT = 'ADD_CGSAT';
export const ADD_CGSAT_SUCCESS = 'ADD_CGSAT_SUCCESS';
export const ADD_CGSAT_FAIL = 'ADD_CGSAT_FAIL';

export const DELETE_CGSAT = 'DELETE_CGSAT';
export const DELETE_CGSAT_SUCCESS = 'DELETE_CGSAT_SUCCESS';
export const DELETE_CGSAT_FAIL = 'DELETE_CGSAT_FAIL';

export const UPDATE_CGSAT = 'UPDATE_CGSAT';
export const UPDATE_CGSAT_SUCCESS = 'UPDATE_CGSAT_SUCCESS';
export const UPDATE_CGSAT_NOTE = 'UPDATE_CGSAT_NOTE';
export const UPDATE_CGSAT_FAIL = 'UPDATE_CGSAT_FAIL';
export const SET_CGSAT_EDITING ='SET_CGSAT_EDITING';