export const GET_ALL_FASTREPORTS = 'GET_ALL_FASTREPORTS';
export const GET_ALL_FASTREPORTS_SUCCESS = 'GET_ALL_FASTREPORTS_SUCCESS';
export const GET_ALL_FASTREPORTS_FAIL = 'GET_ALL_FASTREPORTS_FAIL';

export const SEARCH_FASTREPORT = 'SEARCH_FASTREPORT';
export const SEARCH_FASTREPORT_SUCCESS = 'SEARCH_FASTREPORT_SUCCESS';
export const SEARCH_FASTREPORT_FAIL = 'SEARCH_FASTREPORT_FAIL';

export const GET_ID_FASTREPORT = 'GET_ID_FASTREPORT';
export const GET_ID_FASTREPORT_SUCCESS = 'GET_ID_FASTREPORT_SUCCESS';
export const GET_ID_FASTREPORT_FAIL = 'GET_ID_FASTREPORT_FAIL';


export const ADD_FASTREPORT = 'ADD_FASTREPORT';
export const ADD_FASTREPORT_SUCCESS = 'ADD_FASTREPORT_SUCCESS';
export const ADD_FASTREPORT_FAIL = 'ADD_FASTREPORT_FAIL';

export const DELETE_FASTREPORT = 'DELETE_FASTREPORT';
export const DELETE_FASTREPORT_SUCCESS = 'DELETE_FASTREPORT_SUCCESS';
export const DELETE_FASTREPORT_FAIL = 'DELETE_FASTREPORT_FAIL';

export const UPDATE_FASTREPORT = 'UPDATE_FASTREPORT';
export const UPDATE_FASTREPORT_SUCCESS = 'UPDATE_FASTREPORT_SUCCESS';
export const UPDATE_FASTREPORT_NOTE = 'UPDATE_FASTREPORT_NOTE';
export const UPDATE_FASTREPORT_FAIL = 'UPDATE_FASTREPORT_FAIL';
export const SET_FASTREPORT_EDITING = 'SET_FASTREPORT_EDITING';