export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL';

export const SEARCH_ORDER = 'SEARCH_ORDER';
export const SEARCH_ORDER_SUCCESS = 'SEARCH_ORDER_SUCCESS';
export const SEARCH_ORDER_FAIL = 'SEARCH_ORDER_FAIL';

export const GET_ID_ORDER = 'GET_ID_ORDER';
export const GET_ID_ORDER_SUCCESS = 'GET_ID_ORDER_SUCCESS';
export const GET_ID_ORDER_FAIL = 'GET_ID_ORDER_FAIL';


export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_NOTE = 'UPDATE_ORDER_NOTE';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';
export const SET_ORDER_EDITING ='SET_ORDER_EDITING';