export const GET_ALL_THONGKE = 'GET_ALL_THONGKE';
export const GET_ALL_THONGKE_SUCCESS = 'GET_ALL_THONGKE_SUCCESS';
export const GET_ALL_THONGKE_FAIL = 'GET_ALL_THONGKE_FAIL';

export const SEARCH_THONGKE = 'SEARCH_THONGKE';
export const SEARCH_THONGKE_SUCCESS = 'SEARCH_THONGKE_SUCCESS';
export const SEARCH_THONGKE_FAIL = 'SEARCH_THONGKE_FAIL';

export const GET_ID_THONGKE = 'GET_ID_THONGKE';
export const GET_ID_THONGKE_SUCCESS = 'GET_ID_THONGKE_SUCCESS';
export const GET_ID_THONGKE_FAIL = 'GET_ID_THONGKE_FAIL';

export const ADD_THONGKE = 'ADD_THONGKE';
export const ADD_THONGKE_SUCCESS = 'ADD_THONGKE_SUCCESS';
export const ADD_THONGKE_FAIL = 'ADD_THONGKE_FAIL';

export const DELETE_THONGKE = 'DELETE_THONGKE';
export const DELETE_THONGKE_SUCCESS = 'DELETE_THONGKE_SUCCESS';
export const DELETE_THONGKE_FAIL = 'DELETE_THONGKE_FAIL';

export const UPDATE_THONGKE = 'UPDATE_THONGKE';
export const UPDATE_THONGKE_SUCCESS = 'UPDATE_THONGKE_SUCCESS';
export const UPDATE_THONGKE_NOTE = 'UPDATE_THONGKE_NOTE';
export const UPDATE_THONGKE_FAIL = 'UPDATE_THONGKE_FAIL';
export const SET_THONGKE_EDITING ='SET_THONGKE_EDITING';