export const GET_ALL_TOOLS = 'GET_ALL_TOOLS';
export const GET_ALL_TOOLS_SUCCESS = 'GET_ALL_TOOLS_SUCCESS';
export const GET_ALL_TOOLS_FAIL = 'GET_ALL_TOOLS_FAIL';

export const SEARCH_TOOLS = 'SEARCH_TOOLS';
export const SEARCH_TOOLS_SUCCESS = 'SEARCH_TOOLS_SUCCESS';
export const SEARCH_TOOLS_FAIL = 'SEARCH_TOOLS_FAIL';

export const GET_ID_TOOL = 'GET_ID_TOOL';
export const GET_ID_TOOL_SUCCESS = 'GET_ID_TOOL_SUCCESS';
export const GET_ID_TOOL_FAIL = 'GET_ID_TOOL_FAIL';


export const ADD_TOOL = 'ADD_TOOL';
export const ADD_TOOL_SUCCESS = 'ADD_TOOL_SUCCESS';
export const ADD_TOOL_FAIL = 'ADD_TOOL_FAIL';

export const DELETE_TOOL = 'DELETE_TOOL';
export const DELETE_TOOL_SUCCESS = 'DELETE_TOOL_SUCCESS';
export const DELETE_TOOL_FAIL = 'DELETE_TOOL_FAIL';

export const UPDATE_TOOL = 'UPDATE_TOOL';
export const UPDATE_TOOL_SUCCESS = 'UPDATE_TOOL_SUCCESS';
export const UPDATE_TOOL_FAIL = 'UPDATE_TOOL_FAIL';
export const SET_TOOL_EDITING ='SET_TOOL_EDITING';